name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: |
        yarn install
        yarn build
    - uses: actions/upload-artifact@master
      with:
        name: pr0linker-build
        path: dist/pr0linker.js
